import {defineField, defineType} from 'sanity'

export default defineType({
  name: 'credentials',
  type: 'document',
  title: 'Контакты',
  groups: [
    {
      name: 'email',
      title: 'Электронная почта',
    },
    {
      name: 'phone',
      title: 'Телефон',
    },
    {
      name: 'social',
      title: 'Социальные сети',
    },
    {
      name: 'rss',
      title: 'RSS каналы',
    },
  ],
  fields: [
    defineField({
      name: 'name',
      type: 'string',
      title: 'Наименование',
      description: 'Документ в системе - выбирается произвольно для удобства',
    }),
    defineField({
      name: 'social',
      type: 'array',
      title: 'Социальные сети',
      of: [
        {
          type: 'object',
          preview: {
            select: {
              title: 'label.ru',
              media: 'icon',
            }
          },
          fields: [
            {
              title: 'Наименование',
              name: 'label',
              type: 'i18n.string',
            },
            {
              title: 'Отображать ссылку на сайте',
              name: 'visibility',
              type: 'boolean',
              initialValue: true,
            },
            {
              title: 'Ссылка',
              name: 'link',
              type: 'url',
              validation: Rule => Rule.required(),
            },
            {
              title: 'Иконка',
              name: 'icon',
              type: 'image',
              validation: Rule => Rule.required(),
            },
          ],
        },
      ],
    }),
    defineField({
      name: 'email',
      type: 'object',
      title: 'Электронная почта',
      fieldsets: [{name: 'email', title: 'Электронная почта'}],
      group: 'email',
      fields: [
        {
          title: 'Адрес',
          name: 'email',
          type: 'email',
          validation: Rule => Rule.required(),
        },
        {
          title: 'Отображать почту на сайте',
          name: 'visibility',
          type: 'boolean',
          initialValue: true,
        },
        {
          title: 'Иконка',
          name: 'icon',
          type: 'image',
          validation: Rule => Rule.required(),
        },
      ],
    }),
    defineField({
      name: 'phone',
      type: 'object',
      title: 'Телефон',
      fieldsets: [{name: 'phone', title: 'Телефон'}],
      group: 'phone',
      fields: [
        {
          title: 'Номер',
          name: 'phone',
          type: 'string',
          description: 'в формате +7(XXX)XXX-XXXX',
          validation: (Rule) => Rule.regex(/^\+7\(\d{3}\)\d{3}-\d{4}$/),
        },
        {
          title: 'Отображать телефон на сайте',
          name: 'visibility',
          type: 'boolean',
          initialValue: true,
        },
        {
          title: 'Иконка',
          name: 'icon',
          type: 'image',
          validation: Rule => Rule.required(),
        },
      ],
    }),
    defineField({
      name: 'rss',
      type: 'object',
      title: 'RSS канал',
      fieldsets: [{name: 'rss', title: 'RSS канал'}],
      group: 'rss',
      fields: [
        {
          title: 'Ссылка на канал на русском',
          name: 'linkRu',
          type: 'url',
          validation: Rule => Rule.required(),
        },
        {
          title: 'Ссылка на канал на английском',
          name: 'linkEn',
          type: 'url',
          validation: Rule => Rule.required(),
        },
        {
          title: 'Отображать ссылку на сайте',
          name: 'visibility',
          type: 'boolean',
          initialValue: true,
        },
        {
          title: 'Иконка',
          name: 'icon',
          type: 'image',
          validation: Rule => Rule.required(),
        },
      ],
    }),
    // defineField({
    //   type: 'object',
    //   name: 'email',
    //   fieldsets: [{name: 'email', title: 'Электронная почта'}],
    //   group: 'email',
    //   fields: [
    //     {
    //       title: 'Ссылка',
    //       name: 'email',
    //       type: 'email',
    //       fieldset: 'email',
    //     },
    //     {
    //       title: 'Тип',
    //       name: 'credentialType',
    //       type: 'string',
    //       fieldset: 'email',
    //       options,
    //       validation: Rule => Rule.required(),
    //       initialValue: 'email',
    //     },
    //     {
    //       title: 'Выводить на сайт',
    //       name: 'emailVisibility',
    //       type: 'boolean',
    //       fieldset: 'email',
    //       initialValue: true,
    //     },
    //   ],
    // }),
    // defineField({
    //   type: 'object',
    //   name: 'telegram',
    //   fieldsets: [{name: 'telegram', title: 'Телеграм'}],
    //   group: 'telegram',
    //   fields: [
    //     {
    //       title: 'Ссылка',
    //       name: 'telegramUserName',
    //       type: 'url',
    //       fieldset: 'telegram',
    //     },
    //     {
    //       title: 'Тип',
    //       name: 'credentialType',
    //       type: 'string',
    //       fieldset: 'telegram',
    //       options,
    //       validation: Rule => Rule.required(),
    //       initialValue: 'link',
    //     },
    //     {
    //       title: 'Выводить на сайт',
    //       name: 'telegramVisibility',
    //       type: 'boolean',
    //       fieldset: 'telegram',
    //       initialValue: true,
    //     },
    //   ],
    // }),
    // defineField({
    //   type: 'object',
    //   name: 'vk',
    //   fieldsets: [{name: 'vk', title: 'Вконтакте'}],
    //   group: 'vk',
    //   fields: [
    //     {
    //       title: 'Ссылка',
    //       name: 'vkLink',
    //       type: 'url',
    //       fieldset: 'vk',
    //     },
    //     {
    //       title: 'Тип',
    //       name: 'credentialType',
    //       type: 'string',
    //       fieldset: 'vk',
    //       options,
    //       validation: Rule => Rule.required(),
    //       initialValue: 'link',
    //     },
    //     {
    //       name: 'compTest',
    //       title: 'компутед',
    //       type: 'computedString',
    //       readOnly: true,
    //       options: {
    //         buttonText: 'Refresh',
    //         documentQuerySelection: `
    //         'mimi': vk.credentialType
    //         `,
    //         reduceQueryResult: (result: {
    //           draft? : {mimi: string}
    //           published: {mimi: string}
    //         }) => {return result.published.mimi}
    //       }
    //     },
    //     {
    //       title: 'Выводить сайт',
    //       name: 'vkVisibility',
    //       type: 'boolean',
    //       fieldset: 'vk',
    //       initialValue: false,
    //     },
    //   ],
    // }),
    // defineField({
    //   type: 'object',
    //   name: 'instagram',
    //   fieldsets: [{name: 'instagram', title: 'Instagram'}],
    //   group: 'instagram',
    //   fields: [
    //     {
    //       title: 'Ссылка',
    //       name: 'instagramUserName',
    //       type: 'string',
    //       fieldset: 'instagram',
    //     },
    //     {
    //       title: 'Тип',
    //       name: 'credentialType',
    //       type: 'string',
    //       fieldset: 'instagram',
    //       options,
    //       validation: Rule => Rule.required(),
    //       initialValue: 'link',
    //     },
    //     {
    //       title: 'Выводить на сайт',
    //       name: 'instagramVisibility',
    //       type: 'boolean',
    //       fieldset: 'instagram',
    //       initialValue: true,
    //     },
    //   ],
    // }),
    // defineField({
    //   type: 'object',
    //   name: 'behance',
    //   fieldsets: [{name: 'behance', title: 'Behance'}],
    //   group: 'behance',
    //   fields: [
    //     {
    //       title: 'Ссылка',
    //       name: 'behanceUserName',
    //       type: 'string',
    //       fieldset: 'behance',
    //     },
    //     {
    //       title: 'Тип',
    //       name: 'credentialType',
    //       type: 'string',
    //       fieldset: 'behance',
    //       options,
    //       validation: Rule => Rule.required(),
    //       initialValue: 'link',
    //     },
    //     {
    //       title: 'Выводить на сайт',
    //       name: 'behanceVisibility',
    //       type: 'boolean',
    //       fieldset: 'behance',
    //       initialValue: false,
    //     },
    //   ],
    // }),
    // defineField({
    //   type: 'object',
    //   name: 'facebook',
    //   fieldsets: [{name: 'facebook', title: 'Facebook'}],
    //   group: 'facebook',
    //   fields: [
    //     {
    //       title: 'Ссылка',
    //       name: 'facebookId',
    //       type: 'number',
    //       fieldset: 'facebook',
    //     },
    //     {
    //       title: 'Тип',
    //       name: 'credentialType',
    //       type: 'string',
    //       fieldset: 'facebook',
    //       options,
    //       validation: Rule => Rule.required(),
    //       initialValue: 'link',
    //     },
    //     {
    //       title: 'Выводить на сайт',
    //       name: 'facebookVisibility',
    //       type: 'boolean',
    //       fieldset: 'facebook',
    //       initialValue: true,
    //     },
    //   ],
    // }),

    // defineField({
    //   type: 'object',
    //   name: 'deviantArt',
    //   fieldsets: [{name: 'deviantArt', title: 'Deviant Art'}],
    //   group: 'deviantArt',
    //   fields: [
    //     {
    //       title: 'Ссылка',
    //       name: 'deviantArtUserName',
    //       type: 'string',
    //       fieldset: 'deviantArt',
    //     },
    //     {
    //       title: 'Тип',
    //       name: 'credentialType',
    //       type: 'string',
    //       fieldset: 'deviantArt',
    //       options,
    //       validation: Rule => Rule.required(),
    //       initialValue: 'link',
    //     },
    //     {
    //       title: 'Выводить на сайт',
    //       name: 'deviantArtVisibility',
    //       type: 'boolean',
    //       fieldset: 'deviantArt',
    //       initialValue: false,
    //     },
    //   ],
    // }),
    // defineField({
    //   type: 'object',
    //   name: 'dribble',
    //   fieldsets: [{name: 'dribble', title: 'Dribble'}],
    //   group: 'dribble',
    //   fields: [
    //     {
    //       title: 'Ссылка',
    //       name: 'dribbleUserName',
    //       type: 'string',
    //       fieldset: 'dribble',
    //     },
    //     {
    //       title: 'Тип',
    //       name: 'credentialType',
    //       type: 'string',
    //       fieldset: 'dribble',
    //       options,
    //       validation: Rule => Rule.required(),
    //       initialValue: 'link',
    //     },
    //     {
    //       title: 'Выводить на сайт',
    //       name: 'dribbleVisibility',
    //       type: 'boolean',
    //       fieldset: 'dribble',
    //       initialValue: false,
    //     },
    //   ],
    // }),
    // defineField({
    //   type: 'object',
    //   name: 'linkedIn',
    //   fieldsets: [{name: 'linkedIn', title: 'Linked In'}],
    //   group: 'linkedIn',
    //   fields: [
    //     {
    //       title: 'Ссылка',
    //       name: 'linkedInUserName',
    //       type: 'string',
    //       fieldset: 'linkedIn',
    //     },
    //     {
    //       title: 'Тип',
    //       name: 'credentialType',
    //       type: 'string',
    //       fieldset: 'linkedIn',
    //       options,
    //       validation: Rule => Rule.required(),
    //       initialValue: 'link',
    //     },
    //     {
    //       title: 'Выводить на сайт',
    //       name: 'linkedInVisibility',
    //       type: 'boolean',
    //       fieldset: 'linkedIn',
    //       initialValue: false,
    //     },
    //   ],
    // }),
    // defineField({
    //   type: 'object',
    //   name: 'phone',
    //   fieldsets: [{name: 'phone', title: 'Телефон'}],
    //   group: 'phone',
    //   fields: [
    //     {
    //       title: 'Телефон',
    //       name: 'phoneNumber',
    //       type: 'string',
    //       fieldset: 'phone',
    //       description: 'Номер в формате +7(XXX)XXX-XXXX',
    //     },
    //     {
    //       title: 'Тип',
    //       name: 'credentialType',
    //       type: 'string',
    //       fieldset: 'phone',
    //       options,
    //       validation: Rule => Rule.required().regex(/^\+7\(\d{3}\)\d{3}-\d{4}$/),
    //       initialValue: 'link',
    //     },
    //     {
    //       title: 'Выводить на сайт',
    //       name: 'phoneVisibility',
    //       type: 'boolean',
    //       fieldset: 'phone',
    //       initialValue: false,
    //     },
    //   ],
    // }),
    // defineField({
    //   type: 'object',
    //   name: 'mySpace',
    //   fieldsets: [{name: 'mySpace', title: 'My Space'}],
    //   group: 'mySpace',
    //   fields: [
    //     {
    //       title: 'Ссылка',
    //       name: 'mySpaceUserName',
    //       type: 'string',
    //       fieldset: 'mySpace',
    //     },
    //     {
    //       title: 'Тип',
    //       name: 'credentialType',
    //       type: 'string',
    //       fieldset: 'mySpace',
    //       options,
    //       validation: Rule => Rule.required(),
    //       initialValue: 'link',
    //     },
    //     {
    //       title: 'Выводить на сайт',
    //       name: 'mySpaceVisibility',
    //       type: 'boolean',
    //       fieldset: 'mySpace',
    //       initialValue: false,
    //     },
    //   ],
    // }),
    // defineField({
    //   type: 'object',
    //   name: 'pinterest',
    //   fieldsets: [{name: 'pinterest', title: 'Pinterest'}],
    //   group: 'pinterest',
    //   fields: [
    //     {
    //       title: 'Ссылка',
    //       name: 'pinterestUserName',
    //       type: 'string',
    //       fieldset: 'pinterest',
    //     },
    //     {
    //       title: 'Тип',
    //       name: 'credentialType',
    //       type: 'string',
    //       fieldset: 'pinterest',
    //       options,
    //       validation: Rule => Rule.required(),
    //       initialValue: 'link',
    //     },
    //     {
    //       title: 'Выводить на сайт',
    //       name: 'pinterestVisibility',
    //       type: 'boolean',
    //       fieldset: 'pinterest',
    //       initialValue: false,
    //     },
    //   ],
    // }),
    // defineField({
    //   type: 'object',
    //   name: 'youtube',
    //   fieldsets: [{name: 'youtube', title: 'Youtube'}],
    //   group: 'youtube',
    //   fields: [
    //     {
    //       title: 'Ссылка',
    //       name: 'youtubeUserName',
    //       type: 'string',
    //       fieldset: 'youtube',
    //     },
    //     {
    //       title: 'Тип',
    //       name: 'credentialType',
    //       type: 'string',
    //       fieldset: 'youtube',
    //       options,
    //       validation: Rule => Rule.required(),
    //       initialValue: 'link',
    //     },
    //     {
    //       title: 'Выводить на сайт',
    //       name: 'youtubeVisibility',
    //       type: 'boolean',
    //       fieldset: 'youtube',
    //       initialValue: false,
    //     },
    //   ],
    // }),
  ],
})
